name: Auto Release

on:
  push:
    branches:
      - main
  schedule:
    # Run daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    name: Run CI
    uses: ./.github/workflows/ci.yml

  release:
    name: Create Release
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes since last release
        id: check_changes
        run: |
          # Get the latest release tag (even minor versions only)
          LATEST_RELEASE_TAG=$(git tag -l | grep -E '^v[0-9]+\.[02468]+\.[0-9]+$' | sort -V | tail -1 || echo "")

          if [[ -z "$LATEST_RELEASE_TAG" ]]; then
            echo "No previous release found. Will create first pre-release."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            # Check if there are new commits since the last release (not pre-release)
            COMMITS_SINCE_RELEASE=$(git rev-list --count "$LATEST_RELEASE_TAG"..HEAD)
            
            if [[ $COMMITS_SINCE_RELEASE -gt 0 ]]; then
              echo "Found $COMMITS_SINCE_RELEASE new commits since release $LATEST_RELEASE_TAG"
              echo "has_changes=true" >> $GITHUB_OUTPUT
            else
              echo "No new commits since release $LATEST_RELEASE_TAG"
              echo "has_changes=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Generate version
        if: steps.check_changes.outputs.has_changes == 'true'
        id: version
        run: |
          # Get current version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"

          # Parse version components
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

          # Generate timestamp-based patch version that conforms to VS Code Marketplace limits
          # Format: MMDDHHMM (8 digits max, fits within 2147483647 limit)
          # This ensures uniqueness while staying within valid range
          TIMESTAMP_PATCH=$(date -u +"%m%d%H%M")

          # For auto-release, we create pre-release versions using odd minor numbers
          # Release versions use even minor numbers (e.g., 0.2.x for release, 0.3.x for pre-release)

          # Check if current version is already a pre-release (odd minor)
          if (( MINOR % 2 == 1 )); then
            # Already a pre-release version, use timestamp patch
            NEW_VERSION="${MAJOR}.${MINOR}.${TIMESTAMP_PATCH}"
          else
            # Release version, create new pre-release by incrementing minor to next odd number
            NEW_MINOR=$((MINOR + 1))
            NEW_VERSION="${MAJOR}.${NEW_MINOR}.${TIMESTAMP_PATCH}"
          fi

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Will create pre-release version: v$NEW_VERSION"

      - name: Use Node.js
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies
        if: steps.check_changes.outputs.has_changes == 'true'
        run: npm ci

      - name: Build extension
        if: steps.check_changes.outputs.has_changes == 'true'
        run: npm run compile

      - name: Install vsce
        if: steps.check_changes.outputs.has_changes == 'true'
        run: npm install -g @vscode/vsce

      - name: Update package.json version
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          npm version ${{ steps.version.outputs.version }} --no-git-tag-version

      - name: Package VSIX
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          echo "Packaging pre-release version ${{ steps.version.outputs.version }}"
          vsce package --pre-release --no-git-tag-version
          # List the created VSIX file for debugging
          ls -la *.vsix

      - name: Create tag
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          # Check if tag already exists
          if git rev-parse "v${{ steps.version.outputs.version }}" >/dev/null 2>&1; then
            echo "Tag v${{ steps.version.outputs.version }} already exists, skipping tag creation"
          else
            git tag -a "v${{ steps.version.outputs.version }}" -m "Pre-release v${{ steps.version.outputs.version }}"
            git push origin "v${{ steps.version.outputs.version }}"
          fi

      - name: Generate changelog
        if: steps.check_changes.outputs.has_changes == 'true'
        id: changelog
        run: |
          # Get the previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

          echo "## What's Changed" > changelog.md
          echo "" >> changelog.md

          if [[ -n "$PREV_TAG" ]]; then
            # Get commit messages since last tag
            git log --pretty=format:"* %s (%h)" "$PREV_TAG"..HEAD >> changelog.md
          else
            # First release - show all commits
            git log --pretty=format:"* %s (%h)" >> changelog.md
          fi

          echo "" >> changelog.md
          echo "" >> changelog.md
          echo "**Full Changelog**: https://github.com/${{ github.repository }}/compare/${PREV_TAG}...v${{ steps.version.outputs.version }}" >> changelog.md

      - name: Create GitHub Release
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }} (Pre-release)
          files: "*.vsix"
          body_path: changelog.md
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to VS Code Marketplace
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          if [[ -n "$VSCE_PAT" ]]; then
            echo "Publishing pre-release version ${{ steps.version.outputs.version }} to VS Code Marketplace..."
            echo "Available VSIX files:"
            ls -la *.vsix
            
            VSIX_FILE=$(ls *.vsix | head -1)
            echo "Using VSIX file: $VSIX_FILE"
            
            # Check current package.json version before publishing
            echo "Current package.json version: $(node -p "require('./package.json').version")"
            
            vsce publish --pre-release --packagePath "$VSIX_FILE"
          else
            echo "VSCE_PAT secret not configured. Skipping VS Code Marketplace publish."
          fi
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Summary
        run: |
          if [[ "${{ steps.check_changes.outputs.has_changes }}" == "true" ]]; then
            echo "## Release Summary" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "✅ Successfully created pre-release v${{ steps.version.outputs.version }}!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "- **Version:** v${{ steps.version.outputs.version }} (Pre-release)" >> $GITHUB_STEP_SUMMARY
            echo "- **GitHub Release:** ${{ github.server_url }}/${{ github.repository }}/releases/tag/v${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
            if [[ -n "${{ secrets.VSCE_PAT }}" ]]; then
              echo "- **VS Code Marketplace:** [Published](https://marketplace.visualstudio.com/items?itemName=digitarald.agent-todos)" >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "## No Release Needed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "No changes detected since the last release. Skipping release." >> $GITHUB_STEP_SUMMARY
          fi
